// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: battle_outcomes.sql

package db

import (
	"context"
	"encoding/json"
)

const createBattleOutcome = `-- name: CreateBattleOutcome :exec
INSERT INTO battle_outcomes (
   levy_action_id,
   realm_id,
   attacker,
   defender
) VALUES (
    $1, $2, $3, $4
)
`

type CreateBattleOutcomeParams struct {
	LevyActionID int64           `json:"levy_action_id"`
	RealmID      int64           `json:"realm_id"`
	Attacker     json.RawMessage `json:"attacker"`
	Defender     json.RawMessage `json:"defender"`
}

func (q *Queries) CreateBattleOutcome(ctx context.Context, arg *CreateBattleOutcomeParams) error {
	_, err := q.db.ExecContext(ctx, createBattleOutcome,
		arg.LevyActionID,
		arg.RealmID,
		arg.Attacker,
		arg.Defender,
	)
	return err
}
