// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: conquered_nations.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createConqueredNations = `-- name: CreateConqueredNations :exec
INSERT INTO conquered_nations (
   rm_id,
   owner_nickname,
   country_name,
   cells_jsonb,
   conquered_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateConqueredNationsParams struct {
	RmID          int64           `json:"rm_id"`
	OwnerNickname string          `json:"owner_nickname"`
	CountryName   string          `json:"country_name"`
	CellsJsonb    json.RawMessage `json:"cells_jsonb"`
	ConqueredAt   time.Time       `json:"conquered_at"`
}

func (q *Queries) CreateConqueredNations(ctx context.Context, arg *CreateConqueredNationsParams) error {
	_, err := q.db.ExecContext(ctx, createConqueredNations,
		arg.RmID,
		arg.OwnerNickname,
		arg.CountryName,
		arg.CellsJsonb,
		arg.ConqueredAt,
	)
	return err
}
