// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: indigenous_units.sql

package db

import (
	"context"
)

const findIndigenousUnit = `-- name: FindIndigenousUnit :one
SELECT sector_number, swordmen, archers, lancers, offensive_strength, defensive_strength, created_at FROM indigenous_units
WHERE sector_number = $1
`

func (q *Queries) FindIndigenousUnit(ctx context.Context, sectorNumber int32) (*IndigenousUnit, error) {
	row := q.db.QueryRowContext(ctx, findIndigenousUnit, sectorNumber)
	var i IndigenousUnit
	err := row.Scan(
		&i.SectorNumber,
		&i.Swordmen,
		&i.Archers,
		&i.Lancers,
		&i.OffensiveStrength,
		&i.DefensiveStrength,
		&i.CreatedAt,
	)
	return &i, err
}

const initIndigenousUnits = `-- name: InitIndigenousUnits :exec
COPY indigenous_units (
    sector_number,
    swordmen,
    archers,
    lancers,
    offensive_strength,
    defensive_strength
) FROM '/var/lib/postgresql/data/indigenous_units.csv' 
WITH DELIMITER ',' 
CSV HEADER
`

func (q *Queries) InitIndigenousUnits(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initIndigenousUnits)
	return err
}
