// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: levy_surrenders.sql

package db

import (
	"context"
	"time"
)

const createLevySurrender = `-- name: CreateLevySurrender :exec
INSERT INTO levy_surrenders (
    levy_id,
    receiving_realm_id,
    surrender_reason,
    surrendered_at,
    surrendered_sector_location
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateLevySurrenderParams struct {
	LevyID                    int64     `json:"levy_id"`
	ReceivingRealmID          int64     `json:"receiving_realm_id"`
	SurrenderReason           string    `json:"surrender_reason"`
	SurrenderedAt             time.Time `json:"surrendered_at"`
	SurrenderedSectorLocation int32     `json:"surrendered_sector_location"`
}

func (q *Queries) CreateLevySurrender(ctx context.Context, arg *CreateLevySurrenderParams) error {
	_, err := q.db.ExecContext(ctx, createLevySurrender,
		arg.LevyID,
		arg.ReceivingRealmID,
		arg.SurrenderReason,
		arg.SurrenderedAt,
		arg.SurrenderedSectorLocation,
	)
	return err
}
