// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: member_authorities.sql

package db

import (
	"context"
)

const createMemberAuthority = `-- name: CreateMemberAuthority :exec
INSERT INTO member_authorities (
    rm_id,
    create_unit,
    reinforce_unit,
    move_unit,
    attack_unit,
    private_troops,
    census
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateMemberAuthorityParams struct {
	RmID          int64 `json:"rm_id"`
	CreateUnit    bool  `json:"create_unit"`
	ReinforceUnit bool  `json:"reinforce_unit"`
	MoveUnit      bool  `json:"move_unit"`
	AttackUnit    bool  `json:"attack_unit"`
	PrivateTroops bool  `json:"private_troops"`
	Census        bool  `json:"census"`
}

func (q *Queries) CreateMemberAuthority(ctx context.Context, arg *CreateMemberAuthorityParams) error {
	_, err := q.db.ExecContext(ctx, createMemberAuthority,
		arg.RmID,
		arg.CreateUnit,
		arg.ReinforceUnit,
		arg.MoveUnit,
		arg.AttackUnit,
		arg.PrivateTroops,
		arg.Census,
	)
	return err
}
