// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Realm struct {
	ID              int64     `json:"id"`
	Name            string    `json:"name"`
	OwnerID         int64     `json:"owner_id"`
	CapitalNumber   int32     `json:"capital_number"`
	PoliticalEntity string    `json:"political_entity"`
	CreatedAt       time.Time `json:"created_at"`
}

type Sector struct {
	CellNumber     int32     `json:"cell_number"`
	ProvinceNumber int32     `json:"province_number"`
	RealmID        int64     `json:"realm_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Nickname       string    `json:"nickname"`
	CreatedAt      time.Time `json:"created_at"`
}
