// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: private_coffers_logs.sql

package db

import (
	"context"
	"time"
)

const createBothPrivateCoffersLog = `-- name: CreateBothPrivateCoffersLog :exec
INSERT INTO private_coffers_logs (
    rm_id,
    change_amount,
    total_coffers,
    reason,
    world_time_at
) VALUES 
($1::bigint, $2::int, $3::int, $4::varchar, $5::timestamptz),
($6::bigint, $7::int, $8::int, $9::varchar, $5::timestamptz)
`

type CreateBothPrivateCoffersLogParams struct {
	SourceRmID           int64     `json:"source_rm_id"`
	SourceChangeAmount   int32     `json:"source_change_amount"`
	SourceTotalCoffers   int32     `json:"source_total_coffers"`
	SourceReason         string    `json:"source_reason"`
	WorldTimeAt          time.Time `json:"world_time_at"`
	ReceiverRmID         int64     `json:"receiver_rm_id"`
	ReceiverChangeAmount int32     `json:"receiver_change_amount"`
	ReceiverTotalCoffers int32     `json:"receiver_total_coffers"`
	ReceiverReason       string    `json:"receiver_reason"`
}

func (q *Queries) CreateBothPrivateCoffersLog(ctx context.Context, arg *CreateBothPrivateCoffersLogParams) error {
	_, err := q.db.ExecContext(ctx, createBothPrivateCoffersLog,
		arg.SourceRmID,
		arg.SourceChangeAmount,
		arg.SourceTotalCoffers,
		arg.SourceReason,
		arg.WorldTimeAt,
		arg.ReceiverRmID,
		arg.ReceiverChangeAmount,
		arg.ReceiverTotalCoffers,
		arg.ReceiverReason,
	)
	return err
}
