// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateRealm(ctx context.Context, arg CreateRealmParams) (int64, error)
	CreateRealmSectorsJsonb(ctx context.Context, arg CreateRealmSectorsJsonbParams) error
	CreateSector(ctx context.Context, arg CreateSectorParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	FindRealmWithJson(ctx context.Context, ownerID int64) (FindRealmWithJsonRow, error)
	FindUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
