// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: realm_sectors_jsonb.sql

package db

import (
	"context"
	"encoding/json"
)

const createRealmSectorsJsonb = `-- name: CreateRealmSectorsJsonb :exec
INSERT INTO realm_sectors_jsonb (
    realm_id, cells_jsonb
) VALUES (
    $1, $2
)
`

type CreateRealmSectorsJsonbParams struct {
	RealmID    int64           `json:"realm_id"`
	CellsJsonb json.RawMessage `json:"cells_jsonb"`
}

func (q *Queries) CreateRealmSectorsJsonb(ctx context.Context, arg CreateRealmSectorsJsonbParams) error {
	_, err := q.db.ExecContext(ctx, createRealmSectorsJsonb, arg.RealmID, arg.CellsJsonb)
	return err
}
