// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sector.sql

package db

import (
	"context"
)

const createSector = `-- name: CreateSector :exec
INSERT INTO sectors (
    cell_number,
    province_number,
    realm_id
) VALUES (
    $1, $2, $3
)
`

type CreateSectorParams struct {
	CellNumber     int32 `json:"cell_number"`
	ProvinceNumber int32 `json:"province_number"`
	RealmID        int64 `json:"realm_id"`
}

func (q *Queries) CreateSector(ctx context.Context, arg CreateSectorParams) error {
	_, err := q.db.ExecContext(ctx, createSector, arg.CellNumber, arg.ProvinceNumber, arg.RealmID)
	return err
}
