// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: state_coffers_logs.sql

package db

import (
	"context"
	"time"
)

const createBothStateCoffersLog = `-- name: CreateBothStateCoffersLog :exec
INSERT INTO state_coffers_logs (
    realm_id,
    change_amount,
    total_coffers,
    reason,
    world_time_at
) VALUES 
($1::bigint, $2::int, $3::int, $4::varchar, $5::timestamptz),
($6::bigint, $7::int, $8::int, $9::varchar, $5::timestamptz)
`

type CreateBothStateCoffersLogParams struct {
	SourceRealmID        int64     `json:"source_realm_id"`
	SourceChangeAmount   int32     `json:"source_change_amount"`
	SourceTotalCoffers   int32     `json:"source_total_coffers"`
	SourceReason         string    `json:"source_reason"`
	WorldTimeAt          time.Time `json:"world_time_at"`
	ReceiverRealmID      int64     `json:"receiver_realm_id"`
	ReceiverChangeAmount int32     `json:"receiver_change_amount"`
	ReceiverTotalCoffers int32     `json:"receiver_total_coffers"`
	ReceiverReason       string    `json:"receiver_reason"`
}

func (q *Queries) CreateBothStateCoffersLog(ctx context.Context, arg *CreateBothStateCoffersLogParams) error {
	_, err := q.db.ExecContext(ctx, createBothStateCoffersLog,
		arg.SourceRealmID,
		arg.SourceChangeAmount,
		arg.SourceTotalCoffers,
		arg.SourceReason,
		arg.WorldTimeAt,
		arg.ReceiverRealmID,
		arg.ReceiverChangeAmount,
		arg.ReceiverTotalCoffers,
		arg.ReceiverReason,
	)
	return err
}
