// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: world_time_records.sql

package db

import (
	"context"
	"time"
)

const createWorldTimeRecord = `-- name: CreateWorldTimeRecord :exec
INSERT INTO world_time_records (
    stop_reason,
    world_stopped_at
) VALUES (
    $1, $2
)
`

type CreateWorldTimeRecordParams struct {
	StopReason     string    `json:"stop_reason"`
	WorldStoppedAt time.Time `json:"world_stopped_at"`
}

func (q *Queries) CreateWorldTimeRecord(ctx context.Context, arg *CreateWorldTimeRecordParams) error {
	_, err := q.db.ExecContext(ctx, createWorldTimeRecord, arg.StopReason, arg.WorldStoppedAt)
	return err
}
